#!/usr/bin/env bash
# rebuild-extension.sh — sync userscript → Orion packages (Firefox MV2 + Chrome MV3)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="$ROOT/youtube-mobile-background.user.js"
FF="$ROOT/firefox-extension"
CH="$ROOT/chrome-extension"
TEMPLATE="$FF/content.template.js"

if [[ ! -f "$SRC" ]]; then
  echo "Missing $SRC" >&2
  exit 1
fi
if [[ ! -f "$TEMPLATE" ]]; then
  echo "Missing $TEMPLATE" >&2
  exit 1
fi

VERSION="$(
  python3 - <<'PY' "$SRC"
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r"// @version\s+(\S+)", text)
print(m.group(1) if m else "0.0.0")
PY
)"

RELEASE_LABEL="$(
  python3 - <<'PY' "$SRC" "$VERSION"
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r"// @release-label\s+(\S+)", text)
print(m.group(1) if m else sys.argv[2])
PY
)"

python3 - <<PY
from pathlib import Path
import json, shutil

src = Path("$SRC").read_text(encoding="utf-8")
if src.startswith("// ==UserScript=="):
    end = src.find("// ==/UserScript==")
    if end != -1:
        src = src[end + len("// ==/UserScript=="):].lstrip("\n")
src = src.replace(
    "const SCRIPT_ID = 'vm-yt-mobile-background';",
    "const SCRIPT_ID = 'yt-mobile-orion-ext';",
)
header = """/* Fuck YouTube Premium — page context bundle */
/* Generated by rebuild-extension.sh — edit youtube-mobile-background.user.js, then rebuild. */
"""
page = header + src

ff = Path("$FF")
ch = Path("$CH")
for folder in (ff, ch):
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "page.js").write_text(page, encoding="utf-8")

# Build the stable Orion bootstrap from the content script template.
template = Path("$TEMPLATE").read_text(encoding="utf-8")
content = template
(ff / "content.js").write_text(content, encoding="utf-8")
(ch / "content.js").write_text(content, encoding="utf-8")

icons_dst = ch / "icons"
icons_dst.mkdir(exist_ok=True)
for icon in (ff / "icons").glob("*.png"):
    shutil.copy2(icon, icons_dst / icon.name)

for shared_file in ("background.js", "popup.html", "popup.css", "popup.js"):
    source = ff / shared_file
    if not source.exists():
        raise FileNotFoundError(source)
    shutil.copy2(source, ch / shared_file)

for manifest_path in (ff / "manifest.json", ch / "manifest.json"):
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    data["version"] = "$VERSION"
    manifest_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Updated {manifest_path} -> $VERSION")

print(f"content.js bytes: {(ff / 'content.js').stat().st_size}")
PY

node --check "$FF/page.js"
node --check "$FF/content.js"
node --check "$FF/background.js"
node --check "$FF/popup.js"
node --check "$CH/page.js"
node --check "$CH/content.js"
node --check "$CH/background.js"
node --check "$CH/popup.js"

pack() {
  local dir="$1"
  local out="$2"
  shift 2
  rm -f "$out"
  (
    cd "$dir"
    zip -X -r "$out" "$@"
  )
  python3 - <<PY
import zipfile, json
z = zipfile.ZipFile("$out")
names = z.namelist()
for required in (
    "manifest.json", "content.js", "page.js", "background.js",
    "popup.html", "popup.css", "popup.js"
):
    assert required in names, (required, names)
data = json.loads(z.read("manifest.json"))
assert data.get("version") == "$VERSION", data.get("version")
print("Validated", "$out", "files=", sorted(names))
PY
}

FF_ZIP="$ROOT/fuck-youtube-premium-firefox-${VERSION}.zip"
CH_ZIP="$ROOT/fuck-youtube-premium-chrome-${VERSION}.zip"
ORION_ZIP="$ROOT/fuck-youtube-premium-orion-${VERSION}.zip"
ORION_XPI="$ROOT/fuck-youtube-premium-orion-${VERSION}.xpi"
RELEASE_ZIP="$ROOT/${RELEASE_LABEL}_release.zip"

pack "$FF" "$FF_ZIP" \
  manifest.json content.js page.js background.js popup.html popup.css popup.js \
  icons/icon-48.png icons/icon-96.png icons/icon-128.png

pack "$CH" "$CH_ZIP" \
  manifest.json content.js page.js background.js popup.html popup.css popup.js \
  icons/icon-48.png icons/icon-96.png icons/icon-128.png

ORION_BUILD_DIR="$(mktemp -d "${TMPDIR:-/tmp}/fyp-orion.XXXXXX")"
trap 'rm -rf "$ORION_BUILD_DIR"' EXIT
cp "$FF"/manifest.json "$FF"/content.js "$FF"/page.js \
  "$FF"/background.js "$FF"/popup.html "$FF"/popup.css "$FF"/popup.js \
  "$ORION_BUILD_DIR"/
mkdir -p "$ORION_BUILD_DIR/icons"
cp "$FF"/icons/icon-48.png "$FF"/icons/icon-96.png \
  "$FF"/icons/icon-128.png "$ORION_BUILD_DIR/icons"/

python3 - <<PY
from pathlib import Path
import json

manifest_path = Path("$ORION_BUILD_DIR/manifest.json")
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
manifest.pop("browser_specific_settings", None)
manifest.pop("applications", None)
manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
PY

pack "$ORION_BUILD_DIR" "$ORION_ZIP" \
  manifest.json content.js page.js background.js popup.html popup.css popup.js \
  icons/icon-48.png icons/icon-96.png icons/icon-128.png

cp "$FF_ZIP" "$ORION_XPI"
cp "$CH_ZIP" "$RELEASE_ZIP"
python3 - <<PY
import json, zipfile
with zipfile.ZipFile("$ORION_ZIP") as archive:
    manifest = json.loads(archive.read("manifest.json"))
    assert manifest.get("manifest_version") == 2, manifest
    assert manifest.get("version") == "$VERSION", manifest
    assert "browser_specific_settings" not in manifest, manifest
    assert "applications" not in manifest, manifest
print("Validated", "$ORION_ZIP", "as minimal Orion Manifest V2")

with zipfile.ZipFile("$ORION_XPI") as archive:
    manifest = json.loads(archive.read("manifest.json"))
    assert manifest.get("manifest_version") == 2, manifest
    assert manifest.get("version") == "$VERSION", manifest
    assert manifest.get("browser_specific_settings", {}).get("gecko", {}).get("id")
print("Validated", "$ORION_XPI", "as standard Firefox Manifest V2")

with zipfile.ZipFile("$RELEASE_ZIP") as archive:
    manifest = json.loads(archive.read("manifest.json"))
    assert manifest.get("manifest_version") == 3, manifest
    assert manifest.get("version") == "$VERSION", manifest
    assert manifest.get("action", {}).get("default_popup") == "popup.html", manifest
print("Validated", "$RELEASE_ZIP", "as Orion Chrome Manifest V3 ZIP")

PY

echo
echo "Install this release on Orion iOS (Chrome-format ZIP matching v2.0.20):"
echo "  $RELEASE_ZIP"
echo "Fallback packages:"
echo "  $ORION_ZIP"
echo "  $CH_ZIP"
echo "  $ORION_XPI"
echo "  $FF_ZIP"
ls -la "$RELEASE_ZIP" "$ORION_ZIP" "$ORION_XPI" "$CH_ZIP" "$FF_ZIP"
