#!/usr/bin/env bash
# rebuild-extension.sh — sync userscript → Orion packages (Firefox MV2 + Chrome MV3)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="$ROOT/youtube-mobile-background.user.js"
FF="$ROOT/firefox-extension"
CH="$ROOT/chrome-extension"
TEMPLATE="$FF/content.template.js"

if [[ ! -f "$SRC" ]]; then
  echo "Missing $SRC" >&2
  exit 1
fi
if [[ ! -f "$TEMPLATE" ]]; then
  echo "Missing $TEMPLATE" >&2
  exit 1
fi

VERSION="$(
  python3 - <<'PY' "$SRC"
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r"// @version\s+(\S+)", text)
print(m.group(1) if m else "0.0.0")
PY
)"

python3 - <<PY
from pathlib import Path
import json, shutil

src = Path("$SRC").read_text(encoding="utf-8")
if src.startswith("// ==UserScript=="):
    end = src.find("// ==/UserScript==")
    if end != -1:
        src = src[end + len("// ==/UserScript=="):].lstrip("\n")
src = src.replace(
    "const SCRIPT_ID = 'vm-yt-mobile-background';",
    "const SCRIPT_ID = 'yt-mobile-orion-ext';",
)
header = """/* Fuck YouTube Premium — page context bundle */
/* Generated by rebuild-extension.sh — edit youtube-mobile-background.user.js, then rebuild. */
"""
page = header + src

ff = Path("$FF")
ch = Path("$CH")
for folder in (ff, ch):
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "page.js").write_text(page, encoding="utf-8")

# Build the stable Orion bootstrap from the content script template.
template = Path("$TEMPLATE").read_text(encoding="utf-8")
content = template
(ff / "content.js").write_text(content, encoding="utf-8")
(ch / "content.js").write_text(content, encoding="utf-8")

icons_dst = ch / "icons"
icons_dst.mkdir(exist_ok=True)
for icon in (ff / "icons").glob("*.png"):
    shutil.copy2(icon, icons_dst / icon.name)

for shared_file in ("background.js", "popup.html", "popup.css", "popup.js"):
    source = ff / shared_file
    if not source.exists():
        raise FileNotFoundError(source)
    shutil.copy2(source, ch / shared_file)

for manifest_path in (ff / "manifest.json", ch / "manifest.json"):
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    data["version"] = "$VERSION"
    manifest_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Updated {manifest_path} -> $VERSION")

print(f"content.js bytes: {(ff / 'content.js').stat().st_size}")
PY

node --check "$FF/page.js"
node --check "$FF/content.js"
node --check "$FF/background.js"
node --check "$FF/popup.js"
node --check "$CH/page.js"
node --check "$CH/content.js"
node --check "$CH/background.js"
node --check "$CH/popup.js"

pack() {
  local dir="$1"
  local out="$2"
  shift 2
  rm -f "$out"
  (
    cd "$dir"
    zip -X -r "$out" "$@"
  )
  python3 - <<PY
import zipfile, json
z = zipfile.ZipFile("$out")
names = z.namelist()
for required in (
    "manifest.json", "content.js", "page.js", "background.js",
    "popup.html", "popup.css", "popup.js"
):
    assert required in names, (required, names)
data = json.loads(z.read("manifest.json"))
assert data.get("version") == "$VERSION", data.get("version")
print("Validated", "$out", "files=", sorted(names))
PY
}

FF_ZIP="$ROOT/fuck-youtube-premium-firefox-${VERSION}.zip"
CH_ZIP="$ROOT/fuck-youtube-premium-chrome-${VERSION}.zip"

pack "$FF" "$FF_ZIP" \
  manifest.json content.js page.js background.js popup.html popup.css popup.js \
  icons/icon-48.png icons/icon-96.png icons/icon-128.png

pack "$CH" "$CH_ZIP" \
  manifest.json content.js page.js background.js popup.html popup.css popup.js \
  icons/icon-48.png icons/icon-96.png icons/icon-128.png

echo
echo "Install on Orion iOS (prefer Chrome zip):"
echo "  $CH_ZIP"
echo "  $FF_ZIP"
ls -la "$CH_ZIP" "$FF_ZIP"
